import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const currentYear = new Date().getFullYear();
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <div className="flex min-h-screen flex-col">
          <header className="bg-emerald flex justify-between p-4 text-white">
            <div>
              <Image src="/logo.svg" alt="Logo" width={26} height={26} />
            </div>
          </header>
          <div className="flex flex-1 flex-col items-center justify-center">
            <main className="flex w-full flex-1 flex-col">{children}</main>
          </div>
          <footer className="bg-zinc text-primary mx-auto flex w-full justify-around p-4 px-4">
            © {currentYear} All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
